name: ML-CI-CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      #run: git clone https://github.com/juedemsantos/ml-ci-cd.git
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name:  Install Poetry
      uses: snok/install-poetry@v1
      with: virtualenv-in-project: true

    - name: Load cached venv
      uses: actions/cache@v2
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: venv-${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: make install

    - name: Lint with Flake8
      run: make check